# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_person', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('date_birth', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('U', 'Inseguro')], max_length=1)),
                ('id_auto', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personid', models.CharField(max_length=60, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name_plural': 'Sujetos',
                'verbose_name': 'Sujeto',
            },
        ),
    ]
